# Generated by Django 2.0.2 on 2019-07-11 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='instancia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Profile'),
        ),
    ]
